#!/usr/bin/env python
from lib.command import CommandFactory
from lib.script_utils import load_config, init_logger, ArgumentManager

args = ArgumentManager()

if __name__ == "__main__":
    cfg = load_config(args.config_name())
    init_logger(cfg)

    command = CommandFactory.create(args.action())
    command.exec(cfg, args)
